# Generated by Django 3.2.16 on 2022-11-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro_Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_position', models.CharField(max_length=64, verbose_name='Intro Position')),
            ],
        ),
        migrations.CreateModel(
            name='Intro_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.CharField(max_length=64, verbose_name='Intro')),
                ('intro_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Portfolio.intro_position', verbose_name='Intro Positions')),
            ],
        ),
    ]
