# Generated by Django 3.2.16 on 2022-11-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Intro_Content',
        ),
        migrations.DeleteModel(
            name='Intro_Position',
        ),
    ]
